version: 2

sources:
  - name: weather_dataset
    description: "Dataset containing raw weather data."
    tables:
      - name: staging_table
        description: "Raw data table from the Dataflow pipeline."