version: 2
 
sources:
  - name: weather_data
    schema: weather_dataset  # Replace with your BigQuery dataset name
    tables:
      - name: staging_table  # Replace with your BigQuery table name